function MyMex(filename)
addpath(genpath(pwd));
if(nargin == 0)
	filename = 'TestStieBrockett';
end
mex('-I.\', ...
'-I.\BinaryFiles\', ...
'-I.\Julia\', ...
'-I.\Julia\useless\', ...
'-I.\Manifolds\', ...
'-I.\Manifolds\CpxNStQOrth\', ...
'-I.\Manifolds\ElasticShape\', ...
'-I.\Manifolds\EucPositive\', ...
'-I.\Manifolds\Euclidean\', ...
'-I.\Manifolds\Grassmann\', ...
'-I.\Manifolds\L2Sphere\', ...
'-I.\Manifolds\LowRank\', ...
'-I.\Manifolds\Oblique\', ...
'-I.\Manifolds\OrthGroup\', ...
'-I.\Manifolds\PreShapeCurves\', ...
'-I.\Manifolds\SPDManifold\', ...
'-I.\Manifolds\SPDTensor\', ...
'-I.\Manifolds\Sphere\', ...
'-I.\Manifolds\Stiefel\', ...
'-I.\Matlab\', ...
'-I.\Matlab\ForCpp\', ...
'-I.\Matlab\ForCpp\Boundingbox\', ...
'-I.\Matlab\ForCpp\BrockettLRBFGSVTpaper\', ...
'-I.\Matlab\ForCpp\BrockettNonconvex\', ...
'-I.\Matlab\ForCpp\RepaRotCurves\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\DLandSC\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\algos\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\tools\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\tools\others\', ...
'-I.\Matlab\ForCpp\SPDTensorDLandSC\SPDtensorDL\', ...
'-I.\Matlab\ForCpp\SoftICA\', ...
'-I.\Matlab\ForCpp\SoftICA\New_folder\', ...
'-I.\Matlab\ForCpp\SoftICA\RBFGSNonconvexResults\', ...
'-I.\Matlab\ForCpp\SoftICAnonconvexpaper\', ...
'-I.\Matlab\ForCpp\SoftICAnonconvexpaper\nonconvexResults\', ...
'-I.\Matlab\ForCpp\SparsePCA\', ...
'-I.\Matlab\ForCpp\TOMS_ROPTLIB\', ...
'-I.\Matlab\ForMatlab\', ...
'-I.\Matlab\ForMatlab\FromMelissa\', ...
'-I.\Others\', ...
'-I.\Others\SparseBLAS\', ...
'-I.\Problems\', ...
'-I.\Problems\ElasticCurvesRO\', ...
'-I.\Problems\EucFrechetMean\', ...
'-I.\Problems\EucPosSpCd\', ...
'-I.\Problems\EucQuadratic\', ...
'-I.\Problems\GrassRQ\', ...
'-I.\Problems\KarcherMean\', ...
'-I.\Problems\LRMatrixCompletion\', ...
'-I.\Problems\ObliqueSparsePCA\', ...
'-I.\Problems\ObliqueTestSparsePCA\', ...
'-I.\Problems\OrthBoundingBox\', ...
'-I.\Problems\PreShapePathStraighten\', ...
'-I.\Problems\SPDMean\', ...
'-I.\Problems\SPDTensorDL\', ...
'-I.\Problems\ShapePathStraighten\', ...
'-I.\Problems\SphereConvexHull\', ...
'-I.\Problems\StieBrockett\', ...
'-I.\Problems\StieSoftICA\', ...
'-I.\Problems\StieSparseBrockett\', ...
'-I.\Problems\StieSumBrockett\', ...
'-I.\Problems\WeightedLowrank\', ...
'-I.\Solvers\', ...
'-I.\cwrapper\', ...
'-I.\cwrapper\blas\', ...
'-I.\cwrapper\lapack\', ...
'-I.\test\', ...
['.\test\' filename '.cpp'], ...
'.\Manifolds\Element.cpp', '.\Manifolds\LinearOPE.cpp', '.\Manifolds\Manifold.cpp', '.\Manifolds\ProductElement.cpp', '.\Manifolds\ProductManifold.cpp', '.\Manifolds\SharedSpace.cpp', '.\Manifolds\SmartSpace.cpp', ...
'.\Manifolds\CpxNStQOrth\CSOVariable.cpp', '.\Manifolds\CpxNStQOrth\CSOVector.cpp', '.\Manifolds\CpxNStQOrth\CpxNStQOrth.cpp', ...
'.\Manifolds\ElasticShape\ElasticShape.cpp', '.\Manifolds\ElasticShape\ShapeVariable.cpp', '.\Manifolds\ElasticShape\ShapeVector.cpp', ...
'.\Manifolds\EucPositive\EucPosVariable.cpp', '.\Manifolds\EucPositive\EucPosVector.cpp', '.\Manifolds\EucPositive\EucPositive.cpp', ...
'.\Manifolds\Euclidean\EucVariable.cpp', '.\Manifolds\Euclidean\EucVector.cpp', '.\Manifolds\Euclidean\Euclidean.cpp', ...
'.\Manifolds\Grassmann\GrassVariable.cpp', '.\Manifolds\Grassmann\GrassVector.cpp', '.\Manifolds\Grassmann\Grassmann.cpp', ...
'.\Manifolds\L2Sphere\L2Sphere.cpp', '.\Manifolds\L2Sphere\L2SphereVariable.cpp', '.\Manifolds\L2Sphere\L2SphereVector.cpp', ...
'.\Manifolds\LowRank\LowRank.cpp', '.\Manifolds\LowRank\LowRankVariable.cpp', '.\Manifolds\LowRank\LowRankVector.cpp', ...
'.\Manifolds\Oblique\Oblique.cpp', '.\Manifolds\Oblique\ObliqueVariable.cpp', '.\Manifolds\Oblique\ObliqueVector.cpp', ...
'.\Manifolds\OrthGroup\OrthGroup.cpp', '.\Manifolds\OrthGroup\OrthGroupVariable.cpp', '.\Manifolds\OrthGroup\OrthGroupVector.cpp', ...
'.\Manifolds\PreShapeCurves\PSCVariable.cpp', '.\Manifolds\PreShapeCurves\PSCVector.cpp', '.\Manifolds\PreShapeCurves\PreShapeCurves.cpp', ...
'.\Manifolds\SPDManifold\SPDManifold.cpp', '.\Manifolds\SPDManifold\SPDVariable.cpp', '.\Manifolds\SPDManifold\SPDVector.cpp', ...
'.\Manifolds\SPDTensor\SPDTVariable.cpp', '.\Manifolds\SPDTensor\SPDTVector.cpp', '.\Manifolds\SPDTensor\SPDTensor.cpp', ...
'.\Manifolds\Sphere\Sphere.cpp', '.\Manifolds\Sphere\SphereVariable.cpp', '.\Manifolds\Sphere\SphereVector.cpp', ...
'.\Manifolds\Stiefel\StieVariable.cpp', '.\Manifolds\Stiefel\StieVector.cpp', '.\Manifolds\Stiefel\Stiefel.cpp', ...
'.\Others\ForDebug.cpp', '.\Others\MinPNormConHull.cpp', '.\Others\MyMatrix.cpp', '.\Others\Spline.cpp', '.\Others\Timer.cpp', '.\Others\randgen.cpp', ...
'.\Others\SparseBLAS\nist_spblas.cpp', ...
'.\Problems\Problem.cpp', '.\Problems\juliaProblem.cpp', '.\Problems\mexProblem.cpp', ...
'.\Problems\ElasticCurvesRO\DriverElasticCurvesRO.cpp', '.\Problems\ElasticCurvesRO\ElasticCurvesRO.cpp', ...
'.\Problems\EucFrechetMean\EucFrechetMean.cpp', ...
'.\Problems\EucPosSpCd\EucPosSpCd.cpp', ...
'.\Problems\EucQuadratic\EucQuadratic.cpp', ...
'.\Problems\GrassRQ\GrassRQ.cpp', ...
'.\Problems\KarcherMean\KarcherMean.cpp', ...
'.\Problems\LRMatrixCompletion\LRMatrixCompletion.cpp', ...
'.\Problems\ObliqueSparsePCA\ObliqueSparsePCA.cpp', ...
'.\Problems\ObliqueTestSparsePCA\ObliqueTestSparsePCA.cpp', ...
'.\Problems\OrthBoundingBox\OrthBoundingBox.cpp', ...
'.\Problems\PreShapePathStraighten\PreShapePathStraighten.cpp', ...
'.\Problems\SPDMean\SPDMean.cpp', ...
'.\Problems\SPDTensorDL\SPDTensorDL.cpp', ...
'.\Problems\ShapePathStraighten\ShapePathStraighten.cpp', ...
'.\Problems\SphereConvexHull\SphereConvexHull.cpp', ...
'.\Problems\StieBrockett\StieBrockett.cpp', ...
'.\Problems\StieSoftICA\StieSoftICA.cpp', ...
'.\Problems\StieSparseBrockett\StieSparseBrockett.cpp', ...
'.\Problems\StieSumBrockett\StieSumBrockett.cpp', ...
'.\Problems\WeightedLowrank\WeightedLowRank.cpp', ...
'.\Solvers\LRBFGS.cpp', '.\Solvers\LRBFGSLPSub.cpp', '.\Solvers\LRTRSR1.cpp', '.\Solvers\MRankAdaptive.cpp', '.\Solvers\QuasiNewton.cpp', '.\Solvers\RBFGS.cpp', '.\Solvers\RBFGSLPSub.cpp', '.\Solvers\RBroydenFamily.cpp', '.\Solvers\RCG.cpp', '.\Solvers\RGS.cpp', '.\Solvers\RNewton.cpp', '.\Solvers\RSD.cpp', '.\Solvers\RTRNewton.cpp', '.\Solvers\RTRSD.cpp', '.\Solvers\RTRSR1.cpp', '.\Solvers\RWRBFGS.cpp', '.\Solvers\Solvers.cpp', '.\Solvers\SolversLS.cpp', '.\Solvers\SolversLSLPSub.cpp', '.\Solvers\SolversTR.cpp', ...
['-D' upper(filename)], '-lmwblas', '-lmwlapack', '-largeArrayDims', '-output', ['.\BinaryFiles\' filename ]);
end