function MyMex(filename)
addpath(genpath(pwd));
if(nargin == 0)
	filename = 'TestStieBrockett';
end
mex('-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\BinaryFiles\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Julia\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Julia\useless\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CFixedRank2Factors\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CpxNStQOrth\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\ElasticShape\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\EucPositive\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Euclidean\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Grassmann\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\L2Sphere\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\LowRank\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Oblique\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\OrthGroup\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\PreShapeCurves\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDManifold\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDTensor\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Sphere\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SphereTx\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Stiefel\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconvFromKeWei\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconvFromKeWei\2D\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconvFromKeWei\Aux1\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconvFromKeWei\Main\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\Romberg_noiselet\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\Romberg_noiselet\Measurements\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\Romberg_noiselet\Optimization\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\Romberg_noiselet\Utils\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\minFunc\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\minFunc\compiled\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\minFunc\mex\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\minFunc_2012\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\minFunc_2012\autoDif\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Blinddeconvolution\BlindDeconv_Convex\minFunc_2012\logisticExample\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\Boundingbox\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\BrockettLRBFGSVTpaper\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\BrockettNonconvex\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\PhaseRetrieval\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\RepaRotCurves\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\DLandSC\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\algos\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\tools\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\EucPosSC\tools\others\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SPDTensorDLandSC\SPDtensorDL\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SoftICA\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SoftICA\New_folder\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SoftICA\RBFGSNonconvexResults\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SoftICAnonconvexpaper\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SoftICAnonconvexpaper\nonconvexResults\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\SparsePCA\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForCpp\TOMS_ROPTLIB\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForMatlab\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Matlab\ForMatlab\FromMelissa\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\SparseBLAS\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\fftw\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\CFR2BlindDeconvolution\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\CSOPhaseRetrieval\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ElasticCurvesRO\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucBlindDeconvolution\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucFrechetMean\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucPosSpCd\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucQuadratic\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\GrassRQ\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\KarcherMean\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\LRBlindDeconvolution\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\LRMatrixCompletion\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ObliqueSparsePCA\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ObliqueTestSparsePCA\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\OrthBoundingBox\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\PreShapePathStraighten\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SPDMean\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SPDTensorDL\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ShapePathStraighten\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SphereConvexHull\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SphereTxRQ\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieBrockett\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieSoftICA\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieSparseBrockett\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieSumBrockett\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\WeightedLowrank\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\cwrapper\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\cwrapper\blas\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\cwrapper\lapack\', ...
'-IC:\Users\wh18\Documents\research\Matlab\ROPTLIB\test\', ...
['.\test\' filename '.cpp'], ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Element.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\LinearOPE.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Manifold.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\ProductElement.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\ProductManifold.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SharedSpace.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SmartSpace.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CFixedRank2Factors\CFR2Variable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CFixedRank2Factors\CFR2Vector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CFixedRank2Factors\CFixedRank2Factors.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CpxNStQOrth\CSOVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CpxNStQOrth\CSOVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\CpxNStQOrth\CpxNStQOrth.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\ElasticShape\ElasticShape.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\ElasticShape\ShapeVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\ElasticShape\ShapeVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\EucPositive\EucPosVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\EucPositive\EucPosVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\EucPositive\EucPositive.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Euclidean\EucVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Euclidean\EucVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Euclidean\Euclidean.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Grassmann\GrassVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Grassmann\GrassVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Grassmann\Grassmann.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\L2Sphere\L2Sphere.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\L2Sphere\L2SphereVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\L2Sphere\L2SphereVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\LowRank\LowRank.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\LowRank\LowRankVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\LowRank\LowRankVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Oblique\Oblique.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Oblique\ObliqueVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Oblique\ObliqueVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\OrthGroup\OrthGroup.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\OrthGroup\OrthGroupVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\OrthGroup\OrthGroupVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\PreShapeCurves\PSCVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\PreShapeCurves\PSCVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\PreShapeCurves\PreShapeCurves.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDManifold\SPDManifold.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDManifold\SPDVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDManifold\SPDVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDTensor\SPDTVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDTensor\SPDTVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SPDTensor\SPDTensor.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Sphere\Sphere.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Sphere\SphereVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Sphere\SphereVector.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\SphereTx\SphereTx.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Stiefel\StieVariable.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Stiefel\StieVector.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Manifolds\Stiefel\Stiefel.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\ForDebug.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\MinPNormConHull.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\MyMatrix.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\Spline.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\Timer.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\randgen.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Others\SparseBLAS\nist_spblas.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\Problem.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\juliaProblem.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\mexProblem.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\CFR2BlindDeconvolution\CFR2BlindDeconvolution.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\CSOPhaseRetrieval\CSOPhaseRetrieval.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ElasticCurvesRO\DriverElasticCurvesRO.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ElasticCurvesRO\ElasticCurvesRO.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucBlindDeconvolution\EucBlindDeconvolution.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucFrechetMean\EucFrechetMean.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucPosSpCd\EucPosSpCd.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\EucQuadratic\EucQuadratic.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\GrassRQ\GrassRQ.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\KarcherMean\KarcherMean.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\LRBlindDeconvolution\LRBlindDeconvolution.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\LRMatrixCompletion\LRMatrixCompletion.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ObliqueSparsePCA\ObliqueSparsePCA.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ObliqueTestSparsePCA\ObliqueTestSparsePCA.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\OrthBoundingBox\OrthBoundingBox.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\PreShapePathStraighten\PreShapePathStraighten.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SPDMean\SPDMean.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SPDTensorDL\SPDTensorDL.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\ShapePathStraighten\ShapePathStraighten.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SphereConvexHull\SphereConvexHull.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\SphereTxRQ\SphereTxRQ.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieBrockett\StieBrockett.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieSoftICA\StieSoftICA.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieSparseBrockett\StieSparseBrockett.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\StieSumBrockett\StieSumBrockett.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Problems\WeightedLowrank\WeightedLowRank.cpp', ...
'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\LRBFGS.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\LRBFGSLPSub.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\LRTRSR1.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\MRankAdaptive.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\QuasiNewton.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RBFGS.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RBFGSLPSub.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RBroydenFamily.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RCG.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RGS.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RNewton.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RSD.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RTRNewton.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RTRSD.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RTRSR1.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\RWRBFGS.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\Solvers.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\SolversLS.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\SolversLSLPSub.cpp', 'C:\Users\wh18\Documents\research\Matlab\ROPTLIB\Solvers\SolversTR.cpp', ...
['-D' upper(filename)], '-L.\BinaryFiles\', '-llibfftw3-3', '-llibfftw3f-3', '-llibfftw3l-3', 'C:\Program Files\MATLAB\R2016b\extern\lib\win64\microsoft\libmwblas.lib', 'C:\Program Files\MATLAB\R2016b\extern\lib\win64\microsoft\libmwlapack.lib', '-largeArrayDims', '-output', ['.\BinaryFiles\' filename ]);
end